[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sparql"
version = "0.3.0"
description = "This package provides parsers and serializers for the SPARQL 1.1 Query and Update Language."
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
    { name = "Edmond Chuc", email = "edmond@kurrawong.ai" }
]
dependencies = [
    "lark>=1.1.8",
]

[dependency-groups]
dev = [
    "pytest>=7.4.3",
    "ruff>=0.1.11",
]

[tool.hatch.build.targets.wheel]
packages = ["sparql"]

[tool.ruff]
select = [
    "I001",
    "I002"
]

[tool.pytest.ini_options]
markers = [
    "performance: marks tests as performance benchmarks (select with '-m performance')",
]